// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Asignacion_Pedido_Ruta
{
    public int asignacion_id { get; set; }

    public int pedido_id { get; set; }

    public int ruta_id { get; set; }

    public DateTime fecha_asignacion { get; set; }

    public DateTime? hora_entrega_real { get; set; }

    public virtual Pedidos pedido { get; set; }

    public virtual Rutas ruta { get; set; }
}