// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Clientes
{
    public int cliente_id { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public decimal? latitud { get; set; }

    public decimal? longitud { get; set; }

    public int categoria_id { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();

    public virtual Categorias_Cliente categoria { get; set; }
}