// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Conductores
{
    public int conductor_id { get; set; }

    public int usuario_id { get; set; }

    public string licencia { get; set; }

    public string telefono { get; set; }

    public virtual ICollection<Itinerarios> Itinerarios { get; set; } = new List<Itinerarios>();

    public virtual Usuarios usuario { get; set; }
}