// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Detalle_Pedido
{
    public int detalle_id { get; set; }

    public int pedido_id { get; set; }

    public int? producto_id { get; set; }

    public int cantidad { get; set; }

    public decimal precio_unitario { get; set; }

    public virtual Pedidos pedido { get; set; }

    public virtual Productos producto { get; set; }
}