// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Itinerarios
{
    public int itinerario_id { get; set; }

    public int ruta_id { get; set; }

    public int conductor_id { get; set; }

    public DateOnly fecha { get; set; }

    public TimeOnly hora_inicio { get; set; }

    public TimeOnly? hora_fin { get; set; }

    public virtual Conductores conductor { get; set; }

    public virtual Rutas ruta { get; set; }
}