// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Pedidos
{
    public int pedido_id { get; set; }

    public int cliente_id { get; set; }

    public DateTime fecha_pedido { get; set; }

    public string estado { get; set; }

    public DateTime? hora_estimada_entrega { get; set; }

    public virtual ICollection<Asignacion_Pedido_Ruta> Asignacion_Pedido_Ruta { get; set; } = new List<Asignacion_Pedido_Ruta>();

    public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; } = new List<Detalle_Pedido>();

    public virtual Clientes cliente { get; set; }
}