// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Productos
{
    public int producto_id { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public decimal precio_unitario { get; set; }

    public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; } = new List<Detalle_Pedido>();
}