// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Rutas
{
    public int ruta_id { get; set; }

    public string nombre { get; set; }

    public DateTime? fecha_creacion { get; set; }

    public bool optimizada { get; set; }

    public int zona_id { get; set; }

    public virtual ICollection<Asignacion_Pedido_Ruta> Asignacion_Pedido_Ruta { get; set; } = new List<Asignacion_Pedido_Ruta>();

    public virtual ICollection<Itinerarios> Itinerarios { get; set; } = new List<Itinerarios>();

    public virtual Zonas_Reparto zona { get; set; }
}