// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int usuario_id { get; set; }

    public string nombre { get; set; }

    public string email { get; set; }

    public string contrasena { get; set; }

    public int rol_id { get; set; }

    public virtual ICollection<Conductores> Conductores { get; set; } = new List<Conductores>();

    public virtual Roles rol { get; set; }
}